name: Publicar en CurseForge

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Empaquetar y Publicar
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1471077
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
